import { listItems } from "./store.js";
import { writeVaultFile } from "./vault.js";
import { ymd } from "./dates.js";

// Human-readable markdown mirrors of app data, written into PARA locations so
// Cowork (and Obsidian) can read/search them naturally. These are generated FROM
// the app; edit the data in the app, not the markdown.

const NETWORKING_PATH = "20 - Areas/20.5 - Networking/Networking Contacts.md";

function esc(s) {
  return String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

export function writeNetworkingMirror() {
  const rows = listItems("networking");
  const header =
    `---\ntags: [networking, contacts]\nupdated: ${ymd()}\n---\n\n` +
    `# Networking Contacts\n\n` +
    `> Auto-generated by Mason Hub from the Networking tab. ${rows.length} contacts. ` +
    `Edit in the app (data lives in \`90 - App Data/networking.json\`).\n\n`;

  if (rows.length === 0) {
    writeVaultFile(NETWORKING_PATH, header + "_No contacts yet._\n");
    return;
  }

  const order = { "To reach out": 0, Contacted: 1, Connected: 2, Applied: 3, Interviewing: 4, Offer: 5, Accepted: 6, Rejected: 7 };
  const sorted = [...rows].sort((a, b) => (order[a.status] ?? 8) - (order[b.status] ?? 8) || String(a.name).localeCompare(String(b.name)));

  const table =
    `| Name | Org | Role | Status | Channel | Last contact | Notes |\n` +
    `|---|---|---|---|---|---|---|\n` +
    sorted.map((r) => `| ${esc(r.name)} | ${esc(r.org)} | ${esc(r.role)} | ${esc(r.status)} | ${esc(r.channel)} | ${esc(r.lastContact)} | ${esc(r.notes)} |`).join("\n") +
    "\n";

  // A quick "to reach out" shortlist up top for Cowork to act on.
  const todo = sorted.filter((r) => r.status === "To reach out" || !r.status);
  const shortlist = todo.length
    ? `## Due for outreach (${todo.length})\n` + todo.slice(0, 50).map((r) => `- ${r.name}${r.org ? ` (${r.org})` : ""}`).join("\n") + "\n\n"
    : "";

  writeVaultFile(NETWORKING_PATH, header + shortlist + "## All contacts\n\n" + table);
}
